name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  create-deb:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install meson ninja-build libebook1.2-dev libedata-book1.2-dev libedata-cal2.0-dev evolution-dev
      - run: git clone https://github.com/39aldo39/libdecsync && cd ./libdecsync && git checkout v2.2.1 && make && sudo make install
      - run: meson build
      - run: ninja -C build
      - run: ./create-deb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: evolution-decsync.deb
          path: evolution-decsync.deb
